const DATA_URL='data/candidates_sample.csv';
function getLocalCandidates(){try{return JSON.parse(localStorage.getItem('recruitiq_candidates')||'[]')}catch{return[]}}
function saveLocalCandidates(x){localStorage.setItem('recruitiq_candidates',JSON.stringify(x))}
async function loadSample(){const r=await fetch(DATA_URL);const t=await r.text();return parseCSV(t)}
function parseCSV(text){const lines=text.trim().split(/\r?\n/), headers=lines[0].split(',');return lines.slice(1).map(line=>{const vals=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"')q=!q;else if(c===','&&!q){vals.push(cur);cur=''}else cur+=c}vals.push(cur);const o={};headers.forEach((h,i)=>o[h]=vals[i]??'');return o})}
async function allCandidates(){const sample=await loadSample();return [...getLocalCandidates(),...sample]}
function badge(status){const cls={Selected:'green',Shortlisted:'blue',Interview:'blue',Screening:'orange',Rejected:'red',Applied:'orange'}[status]||'orange';return `<span class="badge ${cls}">${status}</span>`}
async function loadCandidates(){const body=document.getElementById('candidateList');if(!body)return;body.innerHTML='<tr><td colspan="6" class="muted">Loading candidates...</td></tr>';const all=await allCandidates();const q=(document.getElementById('candidateSearch')?.value||'').toLowerCase();const rows=all.filter(c=>[c.CandidateName,c.JobRole,c.Source,c.City,c.CandidateID].join(' ').toLowerCase().includes(q));body.innerHTML=rows.slice(0,100).map(c=>`<tr><td><strong>${c.CandidateName}</strong><br><small class="muted">${c.CandidateID}</small></td><td>${c.JobRole}</td><td>${c.Source}</td><td>${c.ExperienceYears} yrs</td><td>${badge(c.Status)}</td><td><button class="btn btn-secondary" style="padding:7px 10px" onclick="shortlistCandidate('${c.CandidateID}')">${String(c.Shortlisted).toLowerCase()==='true'?'Shortlisted':'Shortlist'}</button></td></tr>`).join('')||'<tr><td colspan="6" class="muted">No candidates found.</td></tr>'}
async function shortlistCandidate(id){const local=getLocalCandidates();const i=local.findIndex(x=>x.CandidateID===id);if(i>=0){local[i].Shortlisted=true;local[i].Status='Shortlisted';saveLocalCandidates(local);loadCandidates();return}alert('Demo dataset records are read-only. Add a candidate first to test the workflow.')}
document.getElementById('candidateSearch')?.addEventListener('input',loadCandidates);
document.getElementById('uploadForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const local=getLocalCandidates();const id='D'+Date.now().toString().slice(-6);const now=new Date().toISOString().slice(0,10);local.unshift({CandidateID:id,CandidateName:f.candidateName.value,Gender:'Not specified',Education:'Not specified',ExperienceYears:f.experience.value,City:f.city.value||'Not specified',JobRole:f.jobRole.value,Source:f.source.value,Skills:'Not specified',ResumeScore:'-',ApplicationDate:now,Status:'Applied',Shortlisted:false,TimeToHireDays:''});saveLocalCandidates(local);document.getElementById('uploadStatus').textContent=`Candidate ${id} added successfully.`;f.reset();});
async function trackApplication(){const id=document.getElementById('candidateId')?.value.trim();const status=document.getElementById('applicationStatus'),history=document.getElementById('progressHistory');if(!id){status.innerHTML='<div class="notice">Please enter a candidate ID.</div>';return}const all=await allCandidates();const c=all.find(x=>x.CandidateID.toLowerCase()===id.toLowerCase());if(!c){status.innerHTML='<div class="notice">Candidate not found. Try C0001 or add a new candidate.</div>';history.innerHTML='';return}status.innerHTML=`<div class="panel" style="padding:18px;background:#f8fafc"><strong>${c.CandidateName}</strong><div class="muted">${c.JobRole} · ${c.Source}</div><div style="margin-top:10px">Current status: ${badge(c.Status)}</div></div>`;const stages=['Applied','Screening','Interview','Shortlisted','Selected'];const idx=Math.max(0,stages.indexOf(c.Status));history.innerHTML=`<div class="timeline">${stages.map((s,i)=>`<div class="timeline-item"><span class="timeline-dot" style="opacity:${i<=idx?1:.25}"></span><div><strong>${s}</strong><div class="muted">${i<=idx?'Completed / reached':'Upcoming stage'}</div></div></div>`).join('')}</div>`}
